interface ICurrency {
  id: Number;
  name: string;
  description: string;
}

export const currency: Array<ICurrency> = [
  { id: 1, name: "AED", description: "United Arab Emirates Dirham" },
  { id: 2, name: "AFN", description: "Afghan Afghani" },
  { id: 3, name: "ALL", description: "Albanian Lek" },
  { id: 4, name: "AMD", description: "Armenian Dram" },
  { id: 5, name: "ANG", description: "Netherlands Antillean Guilder" },
  { id: 6, name: "AOA", description: "Angolan Kwanza" },
  { id: 7, name: "ARS", description: "Argentine Peso" },
  { id: 8, name: "AWG", description: "Aruban Florin" },
  { id: 9, name: "ALL", description: "Albanian Lek" },
  { id: 10, name: "AMD", description: "Armenian Dram" },
  { id: 11, name: "AUD", description: "Australian Dollar" },
  { id: 12, name: "AWG", description: "Netherlands Antillean Guilder" },
  { id: 13, name: "AZN", description: "Azerbaijani Manat" },
  { id: 21, name: "BAM", description: "Bosnia-Herzegovina Convertible Mark" },
  { id: 22, name: "BBD", description: "Barbadian Dollar" },
  { id: 23, name: "BDT", description: "Bangladeshi Taka" },
  { id: 24, name: "BGN", description: "Bulgarian Lev" },
  { id: 25, name: "BHD", description: "Bahraini Dinar" },
  { id: 26, name: "BIF", description: "Burundian Franc" },
  { id: 27, name: "BMD", description: "Bermudan Dollar" },
  { id: 28, name: "BND", description: "Brunei Dollar" },
  { id: 29, name: "BOB", description: "Bolivian Boliviano" },
  { id: 30, name: "BRL", description: "Brazilian Real" },
  { id: 31, name: "BSD", description: "Bahamian Dollar" },
  { id: 32, name: "BTC", description: "Bitcoin" },
  { id: 33, name: "BTN", description: "Bhutanese Ngultrum" },
  { id: 34, name: "BWP", description: "Botswanan Pula" },
  { id: 35, name: "BYR", description: "Belarusian Ruble" },
  { id: 36, name: "BYN", description: "New Belarusian Ruble" },
  { id: 37, name: "BZD", description: "Belize Dollar" },
  { id: 38, name: "CAD", description: "Canadian Dollar" },
  { id: 40, name: "CDF", description: "Congolese Franc" },
  { id: 41, name: "CHF", description: "Swiss Franc" },
  { id: 42, name: "CLF", description: "Chilean Unit of Account" },
  { id: 43, name: "CLP", description: "Chilean Peso" },
  { id: 44, name: "CNY", description: "Chinese Yuan" },
  { id: 45, name: "COP", description: "Colombian Peso" },
  { id: 46, name: "CRC", description: "Costa Rican Colon" },
  { id: 47, name: "CUC", description: "Cuban Convertibla Peso" },
  { id: 48, name: "CUP", description: "Cuban Peso" },
  { id: 49, name: "CVE", description: "Cape Verdean Escudo" },
  { id: 50, name: "CZK", description: "Czech Republic Koruna" },
  { id: 40, name: "DJF", description: "Djiboutian Franc" },
  { id: 41, name: "DKK", description: "Danish Krone" },
  { id: 42, name: "DOP", description: "Dominican Peso" },
  { id: 43, name: "DZD", description: "Algerian Dinar" },
  { id: 44, name: "EGP", description: "Egyptian Pound" },
  { id: 45, name: "ERN", description: "Eritrean Nakfa" },
  { id: 46, name: "ETB", description: "Ethiopian Birr" },
  { id: 47, name: "EUR", description: "Euro" },
  { id: 48, name: "FJD", description: "Fijian Dollar" },
  { id: 49, name: "FKP", description: "Falkland Islands Pound" },
  { id: 50, name: "GBP", description: "British Pound Sterling" },
  { id: 51, name: "GEL", description: "Georgian Lari" },
  { id: 52, name: "GCP", description: "Guernsey Pound" },
  { id: 53, name: "GHS", description: "Ghanaian Cedi" },
  { id: 54, name: "GIP", description: "Gibraltar Pound" },
  { id: 55, name: "GMD", description: "Gambian Dalasi" },
  { id: 56, name: "GNF", description: "Guinean Franc" },
  { id: 57, name: "GTQ", description: "Guatemalan Quetzal" },
  { id: 58, name: "GYD", description: "Guyanaese Dollar" },
  { id: 59, name: "HKD", description: "Hong Kong Dollar" },
  { id: 60, name: "HNL", description: "Honduran Lempira" },
  { id: 61, name: "HRK", description: "Croatian Kuna" },
  { id: 62, name: "HTG", description: "Haitian Gourde" },
  { id: 50, name: "HUF", description: "Hungarian Forint" },
  { id: 51, name: "IDR", description: "Indonesian Rupiah" },
  { id: 52, name: "ILS", description: "Israeli New Sheqel" },
  { id: 53, name: "IMP", description: "Manx pound" },
  { id: 54, name: "INR", description: "Indian Rupee" },
  { id: 55, name: "IQD", description: "Iraqi Dinar" },
  { id: 56, name: "IRR", description: "Iranian Rial" },
  { id: 57, name: "ISK", description: "Icelandic Króna" },
  { id: 58, name: "JEP", description: "Jersey Pound" },
  { id: 59, name: "JMD", description: "Jamaican Dollar" },
  { id: 60, name: "JOD", description: "Jordanian Dinar" },
  { id: 61, name: "JPY", description: "Japanese Yen" },
  { id: 62, name: "KES", description: "Kenyan Shilling" },
  { id: 63, name: "KGS", description: "Kyrgystani Som" },
  { id: 64, name: "KHR", description: "Cambodian Riel" },
  { id: 65, name: "KMF", description: "Comorian Franc" },
  { id: 66, name: "KPW", description: "North Korean Won" },
  { id: 67, name: "KRW", description: "South Korean Won" },
  { id: 68, name: "KWD", description: "Kuwaiti Dinar" },
  { id: 69, name: "KYD", description: "Cayman Islands Dollar" },
  { id: 70, name: "KZT", description: "Kazakhstani Tenge" },
  { id: 71, name: "LAK", description: "Laotian Kip" },
  { id: 72, name: "LBP", description: "Lebanese Pound" },
  { id: 73, name: "LKR", description: "Sri Lankan Rupee" },
  { id: 74, name: "LRD", description: "Liberian Dollar" },
  { id: 75, name: "LSL", description: "Lesotho Loti" },
  { id: 76, name: "LTL", description: "Lithuanian Litas" },
  { id: 77, name: "LVL", description: "Latvian Lats" },
  { id: 78, name: "LYD", description: "Libyan Dinar" },
  { id: 79, name: "MAD", description: "Moroccan Dirham" },
  { id: 80, name: "MDL", description: "Moldovan Leu" },
  { id: 81, name: "MGA", description: "Malagasy Ariary" },
  { id: 82, name: "MKD", description: "Macedonian Denar" },
  { id: 83, name: "MMK", description: "Myanma Kyat" },
  { id: 84, name: "MNT", description: "Mongolian Tugrik" },
  { id: 85, name: "MOP", description: "Macanese Pataca" },
  { id: 86, name: "MRO", description: "Mauritanian Ouguiya" },
  { id: 87, name: "MUR", description: "Mauritian Rupee" },
  { id: 88, name: "MVR", description: "Maldivian Rufiyaa" },
  { id: 89, name: "MWK", description: "Malawian Kwacha" },
  { id: 90, name: "MXN", description: "Mexican Peso" },
  { id: 91, name: "MYR", description: "Malaysian Ringgit" },
  { id: 92, name: "MZN", description: "Mozambican Metical" },
  { id: 93, name: "NAD", description: "Namibian Dollar" },
  { id: 94, name: "NGN", description: "Nigerian Naira" },
  { id: 95, name: "NIO", description: "Nicaraguan Córdoba" },
  { id: 96, name: "NOK", description: "Norwegian Krone" },
  { id: 97, name: "NPR", description: "Nepalese Rupee" },
  { id: 98, name: "NZD", description: "New Zealand Dollar" },
  { id: 99, name: "OMR", description: "Omani Rial" },
  { id: 100, name: "PAB", description: "Panamanian Balboa" },
  { id: 101, name: "PEN", description: "Peruvian Nuevo Sol" },
  { id: 102, name: "PGK", description: "Papua New Guinean Kina" },
  { id: 103, name: "PHP", description: "Philippine Peso" },
  { id: 104, name: "PKR", description: "Pakistani Rupee" },
  { id: 105, name: "PLN", description: "Polish Zloty" },
  { id: 106, name: "PYG", description: "Paraguayan Guarani" },
  { id: 107, name: "QAR", description: "Qatari Rial" },
  { id: 108, name: "RON", description: "Romanian Leu" },
  { id: 109, name: "RSD", description: "Serbian Dinar" },
  { id: 110, name: "RUB", description: "Russian Ruble" },
  { id: 111, name: "RWF", description: "Rwandan Franc" },
  { id: 112, name: "SAR", description: "Saudi Riyal" },
  { id: 113, name: "SBD", description: "SBD,Solomon Islands Dollar" },
  { id: 114, name: "SCR", description: "Seychellois Rupee" },
  { id: 115, name: "SDG", description: "Sudanese Pound" },
  { id: 116, name: "SEK", description: "Swedish Krona" },
  { id: 117, name: "SGD", description: "Singapore Dollar" },
  { id: 118, name: "SHP", description: "Saint Helena Pound" },
  { id: 119, name: "SLL", description: "Sierra Leonean Leone" },
  { id: 120, name: "SOS", description: "Somali Shilling" },
  { id: 121, name: "SRD", description: "Surinamese Dollar" },
  { id: 122, name: "STD", description: "São Tomé and Príncipe Dobra" },
  { id: 123, name: "SVC", description: "Salvadoran Colón" },
  { id: 124, name: "SYP", description: "Syrian Pound" },
  { id: 125, name: "SZL", description: "Swazi Lilangeni" },
  { id: 126, name: "THB", description: "Thai Baht" },
  { id: 127, name: "TJS", description: "Tajikistani Somoni" },
  { id: 128, name: "TMT", description: "Turkmenistani Manat" },
  { id: 129, name: "TND", description: "Tunisian Dinar" },
  { id: 130, name: "TOP", description: "Tongan Paʻanga" },
  { id: 131, name: "TRY", description: "Turkish Lira" },
  { id: 132, name: "TTD", description: "Trinidad and Tobago Dollar" },
  { id: 133, name: "TWD", description: "New Taiwan Dollar" },
  { id: 134, name: "TZS", description: "Tanzanian Shilling" },
  { id: 135, name: "UAH", description: "Ukrainian Hryvnia" },
  { id: 136, name: "UGX", description: "Ugandan Shilling" },
  { id: 137, name: "USD", description: "United States Dollar" },
  { id: 138, name: "UYU", description: "Uruguayan Peso" },
  { id: 139, name: "UZS", description: "Uzbekistan Som" },
  { id: 140, name: "VEF", description: "Venezuelan Bolívar Fuerte" },
  { id: 141, name: "VND", description: "Vietnamese Dong" },
  { id: 142, name: "VUV", description: "Vanuatu Vatu" },
  { id: 143, name: "WST", description: "Samoan Tala" },
  { id: 144, name: "XAF", description: "CFA Franc BEAC" },
  { id: 145, name: "XAG", description: "Silver (troy ounce)" },
  { id: 146, name: "XAU", description: "Gold (troy ounce)" },
  { id: 147, name: "XCD", description: "East Caribbean Dollar" },
  { id: 148, name: "XOF", description: "CFA Franc BCEAO" },
  { id: 149, name: "XDR", description: "Special Drawing Rights" },
  { id: 150, name: "XPF", description: "CFP Franc" },
  { id: 151, name: "YER", description: "Yemeni Rial" },
  { id: 152, name: "ZAR", description: "South African Rand" },
  { id: 153, name: "ZMK", description: "Zambian Kwacha (pre-2013)" },
  { id: 152, name: "ZMW", description: "Zambian Kwacha" },
  { id: 153, name: "ZWL", description: "Zimbabwean Dollar" },
];
